=== mimmi20/BrowserDetector/schema/tests.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "properties": {
      "headers": {
        "type": "object",
        "properties": {
          "user-agent": {
            "type": "string"
          }
        }
      },
      "device": {
        "type": "object",
        "properties": {
          "deviceName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "marketingName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "manufacturer": {
            "type": "string"
          },
          "brand": {
            "type": "string"
          },
          "display": {
            "type": "object",
            "properties": {
              "width": {
                "anyOf": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "height": {
                "anyOf": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "touch": {
                "anyOf": [
                  {
                    "type": "boolean"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "type": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            },
            "required": [
              "width",
              "height",
              "touch",
              "type"
            ]
          },
          "dualOrientation": {
            "type": "boolean"
          },
          "type": {
            "type": "string"
          }
        },
        "required": [
          "deviceName",
          "marketingName",
          "manufacturer",
          "brand",
          "display",
          "dualOrientation",
          "type"
        ]
      },
      "browser": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "modus": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "integer"
              }
            ]
          },
          "version": {
            "type": "string"
          },
          "manufacturer": {
            "type": "string"
          },
          "bits": {
            "type": "integer"
          },
          "type": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "modus",
          "version",
          "manufacturer",
          "bits",
          "type"
        ]
      },
      "os": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "marketingName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "version": {
            "type": "string"
          },
          "manufacturer": {
            "type": "string"
          },
          "bits": {
            "type": "integer"
          }
        },
        "required": [
          "name",
          "marketingName",
          "version",
          "manufacturer",
          "bits"
        ]
      },
      "engine": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "version": {
            "type": "string"
          },
          "manufacturer": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "version",
          "manufacturer"
        ]
      }
    },
    "required": [
      "headers",
      "device",
      "browser",
      "os",
      "engine"
    ]
  }
}

=== mimmi20/BrowserDetector/tests/data/device/neofonie.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (X11; U; Linux i686; de-DE) AppleWebKit/534.3 (KHTML, like Gecko) WeTab-Browser Safari/534.3"
    },
    "device": {
      "deviceName": "WeTab",
      "marketingName": "WeTab",
      "manufacturer": "WeTab",
      "brand": "WeTab",
      "display": {
        "width": 1366,
        "height": 768,
        "touch": true,
        "type": "FWXGA",
        "size": null
      },
      "dualOrientation": true,
      "type": "tablet",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "WeTab Browser",
      "modus": null,
      "version": "0.0.0",
      "manufacturer": "Unknown",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "MeeGo",
      "marketingName": "MeeGo",
      "version": "0.0.0",
      "manufacturer": "LinuxFoundation",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.3.0",
      "manufacturer": "Apple"
    }
  }
]

=== mimmi20/BrowserDetector/tests/data/device/yuntab.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 5.1; K107 Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Safari/537.36"
    },
    "device": {
      "deviceName": "K107",
      "marketingName": "K107",
      "manufacturer": "Yuntab",
      "brand": "Yuntab",
      "type": "fone-pad",
      "display": {
        "width": 1280,
        "height": 800,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Android WebView",
      "modus": null,
      "version": "58.0.3029.83",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "5.1.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 5.1; K17 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
    },
    "device": {
      "deviceName": "K17",
      "marketingName": "K17",
      "manufacturer": "Yuntab",
      "brand": "Yuntab",
      "type": "fone-pad",
      "display": {
        "width": 1280,
        "height": 800,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "67.0.3396.87",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "5.1.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  }
]

=== mimmi20/BrowserDetector/tests/data/device/stell.json
[
  {
    "headers": {
      "user-agent": "UCWEB/2.0 (Linux; U; Opera Mini/7.1.32052/30.3697; ru; S-TELL_M260) U2/1.0.0 UCBrowser/10.1.2.571 Mobile"
    },
    "device": {
      "deviceName": "M260",
      "marketingName": "M260",
      "manufacturer": "Stell",
      "brand": "Stell",
      "display": {
        "width": 480,
        "height": 800,
        "touch": true,
        "type": "WVGA (variant 3)",
        "size": null
      },
      "dualOrientation": true,
      "type": "smartphone",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "UC Browser",
      "modus": null,
      "version": "10.1.2.571",
      "manufacturer": "UcWeb",
      "bits": 32,
      "type": "transcoder"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "0.0.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "U2",
      "version": "1.0.0",
      "manufacturer": "UcWeb"
    }
  }
]

=== mimmi20/BrowserDetector/tests/data/device/ouku.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 7.0; F888 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.80 Safari/537.36"
    },
    "device": {
      "deviceName": "F888",
      "marketingName": "F888",
      "manufacturer": "Ouku",
      "brand": "Ouku",
      "display": {
        "width": 1280,
        "height": 800,
        "touch": true,
        "type": "unknown"
      },
      "dualOrientation": true,
      "type": "fone-pad"
    },
    "browser": {
      "name": "Android WebView",
      "modus": null,
      "version": "70.0.3538.80",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "7.0.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  }
]

=== mimmi20/BrowserDetector/tests/data/device/qmax.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.4.2; QT-10 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36"
    },
    "device": {
      "deviceName": "QT-10",
      "marketingName": "QT-10",
      "manufacturer": "Qmax",
      "brand": "Qmax",
      "display": {
        "width": null,
        "height": null,
        "touch": false,
        "type": "unknown",
        "size": null
      },
      "dualOrientation": false,
      "type": "tv-media-player",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "Android WebView",
      "modus": null,
      "version": "30.0.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.4.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  }
]

=== mimmi20/BrowserDetector/tests/data/device/star.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.0.4; en-us; N9500 Build/IMM76I) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "N9500",
      "marketingName": "N9500",
      "manufacturer": "Star",
      "brand": "Star",
      "type": "smartphone",
      "display": {
        "width": 720,
        "height": 1280,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.0.4",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "Apple"
    }
  },
  {
    "headers": {
      "user-agent": "UCWEB/2.0 (MIDP-2.0; U; Adr 4.3.3; ru; GT-9000) U2/1.0.0 UCBrowser/9.9.0.543 U2/1.0.0 Mobile"
    },
    "device": {
      "deviceName": "GT-9000",
      "marketingName": "H5W",
      "manufacturer": "Star",
      "brand": "Star",
      "type": "smartphone",
      "display": {
        "width": 480,
        "height": 800,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "UC Browser",
      "modus": null,
      "version": "9.9.0.543",
      "manufacturer": "UcWeb",
      "bits": 32,
      "type": "transcoder"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.3.3",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "U2",
      "version": "1.0.0",
      "manufacturer": "UcWeb"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.2.2; N8000 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 YaBrowser/15.2.2214.3725.01 Safari/537.36"
    },
    "device": {
      "deviceName": "N8000",
      "marketingName": "Note 3",
      "manufacturer": "Star",
      "brand": "Star",
      "type": "smartphone",
      "display": {
        "width": 540,
        "height": 960,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Yandex Browser",
      "modus": null,
      "version": "15.2.2214.3725.01",
      "manufacturer": "Yandex",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.2.1; 9930i Build/JOP40D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.92 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "9930i",
      "marketingName": "Galaxy S3",
      "manufacturer": "Star",
      "brand": "Star",
      "type": "smartphone",
      "display": {
        "width": 480,
        "height": 854,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "30.0.1599.92",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.2.2; N8800 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.92 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "N8800",
      "marketingName": "N8800",
      "manufacturer": "Star",
      "brand": "Star",
      "type": "smartphone",
      "display": {
        "width": 540,
        "height": 960,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "43.0.2357.92",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.1; fr-fr; N9600 Build/JOP40D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "N9600",
      "marketingName": "N9600",
      "manufacturer": "Star",
      "brand": "Star",
      "type": "smartphone",
      "display": {
        "width": null,
        "height": null,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "Apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.2.2; N9700 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "N9700",
      "marketingName": "N9700",
      "manufacturer": "Star",
      "brand": "Star",
      "type": "smartphone",
      "display": {
        "width": 540,
        "height": 960,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "34.0.1847.114",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.2; it-it; N9800 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "N9800",
      "marketingName": "N9800",
      "manufacturer": "Star",
      "brand": "Star",
      "type": "smartphone",
      "display": {
        "width": 720,
        "height": 1280,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "Apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.1.1; fr-fr; N9977 Build/JRO03C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "N9977",
      "marketingName": "Note 2",
      "manufacturer": "Star",
      "brand": "Star",
      "type": "smartphone",
      "display": {
        "width": 480,
        "height": 800,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.1.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "Apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.4.2; N9000 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "N9000",
      "marketingName": "Note 3 III",
      "manufacturer": "Star",
      "brand": "Star",
      "type": "smartphone",
      "display": {
        "width": null,
        "height": null,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Android WebView",
      "modus": null,
      "version": "30.0.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.4.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  }
]

=== mimmi20/BrowserDetector/tests/data/device/noain.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.0; zh-CN; NOAIN A900S Build/GRK39F) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.3.2.559 U3/0.8.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "A900S",
      "marketingName": "A900S",
      "manufacturer": "Noain",
      "brand": "Noain",
      "type": "smartphone",
      "display": {
        "width": 480,
        "height": 800,
        "touch": true,
        "type": null
      },
      "dualOrientation": false
    },
    "browser": {
      "name": "UC Browser",
      "modus": null,
      "version": "10.3.2.559",
      "manufacturer": "UcWeb",
      "bits": 32,
      "type": "transcoder"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "U3",
      "version": "0.8.0",
      "manufacturer": "UcWeb"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.2; zh-cn; NOAIN A913 Build/NOAINNOAIN) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 baiduboxapp/042_0.4_diordna_458_084/NIAON_71_2.2.4_319A+NIAON/1000418d/E29E98703F45BF1A99367DD1C0738595%7C836550000196968/1"
    },
    "device": {
      "deviceName": "A913",
      "marketingName": "A913",
      "manufacturer": "Noain",
      "brand": "Noain",
      "type": "smartphone",
      "display": {
        "width": 720,
        "height": 1280,
        "touch": true,
        "type": null
      },
      "dualOrientation": false
    },
    "browser": {
      "name": "Baidu Box App",
      "modus": null,
      "version": "042.0.4",
      "manufacturer": "Baidu",
      "bits": 32,
      "type": "application"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "Apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.4.4; zh-CN; NOAIN_M15 Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.2.0.535 U3/0.8.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "M15",
      "marketingName": "M15",
      "manufacturer": "Noain",
      "brand": "Noain",
      "type": "smartphone",
      "display": {
        "width": 720,
        "height": 1280,
        "touch": true,
        "type": null
      },
      "dualOrientation": false
    },
    "browser": {
      "name": "UC Browser",
      "modus": null,
      "version": "10.2.0.535",
      "manufacturer": "UcWeb",
      "bits": 32,
      "type": "transcoder"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.4.4",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "U3",
      "version": "0.8.0",
      "manufacturer": "UcWeb"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.2; zh-CN; NOAIN M6 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.5.2.598 U3/0.8.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "M6",
      "marketingName": "M6",
      "manufacturer": "Noain",
      "brand": "Noain",
      "type": "smartphone",
      "display": {
        "width": 480,
        "height": 854,
        "touch": true,
        "type": null
      },
      "dualOrientation": false
    },
    "browser": {
      "name": "UC Browser",
      "modus": null,
      "version": "10.5.2.598",
      "manufacturer": "UcWeb",
      "bits": 32,
      "type": "transcoder"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "U3",
      "version": "0.8.0",
      "manufacturer": "UcWeb"
    }
  }
]

=== mimmi20/BrowserDetector/tests/data/device/nikon.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 2.3.3; ja-jp; COOLPIX S800c Build/CP01_WW) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"
    },
    "device": {
      "deviceName": "Coolpix S800c",
      "marketingName": "Coolpix S800c",
      "manufacturer": "Nikon",
      "brand": "Nikon",
      "display": {
        "width": 480,
        "height": 800,
        "touch": true,
        "type": "WVGA (variant 3)",
        "size": null
      },
      "dualOrientation": true,
      "type": "digital-camera",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "2.3.3",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "533.1.0",
      "manufacturer": "Apple"
    }
  }
]
