=== mimmi20/BrowserDetector/schema/tests.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "properties": {
      "headers": {
        "type": "object",
        "properties": {
          "user-agent": {
            "type": "string"
          }
        }
      },
      "device": {
        "type": "object",
        "properties": {
          "deviceName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "marketingName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "manufacturer": {
            "type": "string"
          },
          "brand": {
            "type": "string"
          },
          "display": {
            "type": "object",
            "properties": {
              "width": {
                "anyOf": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "height": {
                "anyOf": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "touch": {
                "anyOf": [
                  {
                    "type": "boolean"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "type": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            },
            "required": [
              "width",
              "height",
              "touch",
              "type"
            ]
          },
          "dualOrientation": {
            "type": "boolean"
          },
          "type": {
            "type": "string"
          }
        },
        "required": [
          "deviceName",
          "marketingName",
          "manufacturer",
          "brand",
          "display",
          "dualOrientation",
          "type"
        ]
      },
      "browser": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "modus": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "integer"
              }
            ]
          },
          "version": {
            "type": "string"
          },
          "manufacturer": {
            "type": "string"
          },
          "bits": {
            "type": "integer"
          },
          "type": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "modus",
          "version",
          "manufacturer",
          "bits",
          "type"
        ]
      },
      "os": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "marketingName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "version": {
            "type": "string"
          },
          "manufacturer": {
            "type": "string"
          },
          "bits": {
            "type": "integer"
          }
        },
        "required": [
          "name",
          "marketingName",
          "version",
          "manufacturer",
          "bits"
        ]
      },
      "engine": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "version": {
            "type": "string"
          },
          "manufacturer": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "version",
          "manufacturer"
        ]
      }
    },
    "required": [
      "headers",
      "device",
      "browser",
      "os",
      "engine"
    ]
  }
}

=== mimmi20/BrowserDetector/tests/data/device/pandigital.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 2.3.1; en-us; pandigitalsprnova1/sourceidDL00000025) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"
    },
    "device": {
      "deviceName": "SuperNova",
      "marketingName": "SuperNova",
      "manufacturer": "Pandigital",
      "brand": "Pandigital",
      "type": "tablet",
      "display": {
        "width": 800,
        "height": 600,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "2.3.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "533.1.0",
      "manufacturer": "Apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android Eclair; md-us Build/pandigitalopc1/sourceidDL00000009) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17"
    },
    "device": {
      "deviceName": "Novel",
      "marketingName": "Novel",
      "manufacturer": "Pandigital",
      "brand": "Pandigital",
      "type": "tablet",
      "display": {
        "width": 800,
        "height": 600,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "2.1.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "530.17.0",
      "manufacturer": "Apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 2.0; en-us; pandigital9hr) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17"
    },
    "device": {
      "deviceName": "9hr",
      "marketingName": "9hr",
      "manufacturer": "Pandigital",
      "brand": "Pandigital",
      "type": "tablet",
      "display": {
        "width": null,
        "height": null,
        "touch": true,
        "type": null
      },
      "dualOrientation": true
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "2.0.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "530.17.0",
      "manufacturer": "Apple"
    }
  }
]

=== mimmi20/BrowserDetector/tests/data/device/doro.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.4.2; Doro Liberto 820 Mini Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.109 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "Liberto 820 Mini",
      "marketingName": "Liberto 820 Mini",
      "manufacturer": "Doro",
      "brand": "Doro",
      "display": {
        "width": 480,
        "height": 800,
        "touch": true,
        "type": "WVGA (variant 3)",
        "size": null
      },
      "dualOrientation": true,
      "type": "smartphone",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "40.0.2214.109",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.4.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 5.1.1; Doro 8030/8031/8028 Build/EU_RET_03.14.02; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "8030",
      "marketingName": "8030",
      "manufacturer": "Doro",
      "brand": "Doro",
      "display": {
        "width": 480,
        "height": 854,
        "touch": true,
        "type": "FWVGA (variant 1)",
        "size": null
      },
      "dualOrientation": true,
      "type": "smartphone",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "Android WebView",
      "modus": null,
      "version": "58.0.3029.83",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "5.1.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 5.1.1; Doro Liberto 825 Build/EU_RET_04.10.00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "Liberto 825",
      "marketingName": "Liberto 825",
      "manufacturer": "Doro",
      "brand": "Doro",
      "display": {
        "width": 720,
        "height": 1280,
        "touch": true,
        "type": "HD/WXGA",
        "size": null
      },
      "dualOrientation": true,
      "type": "smartphone",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "Android WebView",
      "modus": null,
      "version": "55.0.2883.91",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "5.1.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.4.2; Doro Liberto 820 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.94 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "Liberto 820",
      "marketingName": "Liberto 820",
      "manufacturer": "Doro",
      "brand": "Doro",
      "display": {
        "width": 540,
        "height": 960,
        "touch": true,
        "type": "qHD",
        "size": null
      },
      "dualOrientation": true,
      "type": "smartphone",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "41.0.2272.94",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.4.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 5.1.1; Doro 8031 Build/EU_TMO_02.19.00) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "8031",
      "marketingName": "8031",
      "manufacturer": "Doro",
      "brand": "Doro",
      "display": {
        "width": 480,
        "height": 854,
        "touch": true,
        "type": "FWVGA (variant 1)",
        "size": null
      },
      "dualOrientation": true,
      "type": "smartphone",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "68.0.3440.91",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "5.1.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 7.0; Doro 8040 Build/S10A_502) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "8040",
      "marketingName": "8040",
      "manufacturer": "Doro",
      "brand": "Doro",
      "display": {
        "width": null,
        "height": null,
        "touch": true,
        "type": "unknown",
        "size": null
      },
      "dualOrientation": true,
      "type": "smartphone",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "Chrome",
      "modus": null,
      "version": "64.0.3282.137",
      "manufacturer": "Google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "7.0.0",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "Google"
    }
  }
]

=== mimmi20/BrowserDetector/tests/data/device/vertex.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.2; ru; Impress_L Build/JDQ39) AppleWebKit/528.5+ (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1 UCBrowser/9.5.1.494 Mobile"
    },
    "device": {
      "deviceName": "Impress L",
      "marketingName": "Impress L",
      "manufacturer": "Vertex",
      "brand": "Vertex",
      "display": {
        "width": 540,
        "height": 960,
        "touch": true,
        "type": "qHD",
        "size": null
      },
      "dualOrientation": true,
      "type": "smartphone",
      "simCount": 0,
      "market": {
        "regions": [],
        "countries": [],
        "vendors": []
      },
      "connections": []
    },
    "browser": {
      "name": "UC Browser",
      "modus": null,
      "version": "9.5.1.494",
      "manufacturer": "UcWeb",
      "bits": 32,
      "type": "transcoder"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "528.5.0",
      "manufacturer": "Apple"
    }
  }
]
